### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by geng-lee** [Novartis/EQP-QM#1]
Hi,

I get an error when running eqp-setup.sh. 
ValueError: not enough values to unpack (expected 3, got 1)

how to solve this problem? The log details are as follows:

```
eqp-setup.sh gencode.v29.annotation.gtf data

Directory data/gtf-files does not exist ... creating
Directory data/bed-files does not exist ... creating
Directory data/map-files does not exist ... creating
Adding exon ids to GTF file
Reading file: gencode.v29.annotation.gtf
Writing to file: data/gtf-files/gencode.v29.annotation.gtf
......................................................
1262773 exon entries found.
Creating junction - exon mapping file - this can take a while
[1] "Reading data/gtf-files/gencode.v29.annotation.gtf: "
[1] "Found 1262773 rows."
[1] "Generating a list with unique exons for each gene"
[1] "Computing exon ranks"
[1] "598354 exon gene rank mappings found for 597906 exons."
[1] "Finding exon indices"
[1] "Computing combinations"
[1] "Writing 10065660 junction exon mapping records to file data/map-files/gencode.v29.annotation_junction_exon.map"
Compressing file junction - exon mapping file data/map-files/gencode.v29.annotation_junction_exon.map
Creating exon - exon map file data/map-files/gencode.v29.annotation_exon_exon.map
Reading file: data/gtf-files/gencode.v29.annotation.gtf
Traceback (most recent call last):
  File "/Volumes/LaCie/data_analyze/qh/22_7_20_encode/test/EQP-QM/util-scripts/createExonExonMapFile.py", line 154, in <module>
    exonIdExonLocationMap, exonLocationExonIdMap = readGtfFile(gtfFilename)
  File "/Volumes/LaCie/data_analyze/qh/22_7_20_encode/test/EQP-QM/util-scripts/createExonExonMapFile.py", line 106, in readGtfFile
    annotationType, annotationValue, annotationEmpty = annotationEntry.strip().split('"')
ValueError: not enough values to unpack (expected 3, got 1)
Problem with createExonExonMapFile.py -g data/map-files/gencode.v29.annotation_exon_gene.map -b data/bed-files/gencode.v29.annotation_genome_exons.bed data/gtf-files/gencode.v29.annotation.gtf
 data/map-files/gencode.v29.annotation_exon_exon.map ... exiting
```

best,
Jamie

**Comment by dfermin** [comment]
The problem has to do with Gencode's GTF file.
If you use the Ensembl GTF file there is no error. 
HTH

**Comment by johnmalib** [comment]
During a multiple value assignment, the ValueError: not enough values to unpack occurs when either you have fewer objects to assign than variables, or you have more variables than objects. This error caused by the mismatch between the number of values returned and the number of variables in the assignment statement. This error happened mostly in the case of using [python split](http://net-informations.com/python/file/split.htm)  function. Verify the assignment variables. If the number of assignment variables is greater than the total number of variables, delete the excess variable from the assignment operator. The number of objects returned, as well as the number of variables available are the same. 

To see what line is causing the issue, you could add some debug statements like this:

```
if len(line.split()) != "xx":
    print line
```

This will resolve the value error.
